### ISSUE TITLE
Kernel stuck after initrd

### ISSUE THREAD

**Issue by dragonchaser** [rancher-sandbox/cOS-toolkit#785] opened 2021-10-12 11:56 UTC
**cos-toolkit version:** cos-system 0.7.0-7

**CPU architecture, OS, and Version:** aarch64 on rpi4 cos-green

**Describe the bug**

When trying to boot a rpi4 using u-boot with a chain-loaded grub, the kernel gets stuck without any output after loading the initrd.
(see logs section below for output)

**To Reproduce**

Partition an SD-Card into two partions, one formatted with FAT containing the boot data created using https://github.com/dragonchaser/pi-bootbuilder the second one formatted with ext4 containing the cos-system from quay.io (quay.io/costoolkit/releases-green-arm64:cos-system-0.7.0-7)

**Expected behavior** cOS should be booting or there should be at least an output why the kernel is stuck/failing.

**Logs**

```
Loading Linux 5.3.18-59.24-default ...
Loading initial ramdisk ...
EFI stub: Booting Linux Kernel...
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services and installing virtual address map...
```

**Comment by mudler** [comment] 2021-10-21 08:16
Marking it as dependent on #526. A U-boot package is needed to debug any further on the native HW

**Comment by mudler** [comment] 2021-11-02 09:20
@kkaempf tried it and can't reproduce it anymore. Although the boot times seems to be rather slow on a RPI3 with 1 GB of RAM (during initrd decompression)

**Comment by mudler** [comment] 2021-11-18 15:08
I'm actually seeing the same thing when running the JeOS image for Odroid c2, and images created with openSUSE in #867

**Comment by kkaempf** [comment] 2021-11-18 16:45
When I wait long enough, this happens:

```
[   23.876403] usbcore: registered new interface driver smsc95xx
[  191.502897] dracut-initqueue[494]: Warning: dracut-initqueue timeout - starting timeout scripts
...
[  274.761248] dracut-initqueue[494]: Warning: dracut-initqueue timeout - starting timeout scripts
[  274.800839] dracut-initqueue[494]: Warning: Could not boot.
         Starting Dracut Emergency Shell...
Warning: /dev/disk/by-label/COS_LIVE does not exist
Warning: /dev/root does not exist

Generating "/run/initramfs/rdsosreport.txt"


Entering emerPress Enter for maintenance
(or press Control-D to continue): [ TIME ] Timed out waiting for device /dev/mapper/live-rw.
[DEPEND] Dependency failed for /sysroot.
[DEPEND] Dependency failed for Initrd Root File System.
[DEPEND] Dependency failed for Relo�…figuration from the Real Root.
[DEPEND] Dependency failed for cOS system early rootfs setup.
[DEPEND] Dependency failed for Initrd File Systems.
[DEPEND] Dependency failed for cOS �…amfs setup before switch root.
[DEPEND] Dependency failed for cOS system immutable rootfs mounts.
[ 3014.743793] dracut-initqueue[2690]: Job for dracut-emergency.service canceled.
[  OK  ] Stopped Dispatch Password �…ts to Console Directory Watch.
[  OK  ] Stopped target Basic System.
[  OK  ] Stopped target System Initialization.
[  OK  ] Started Emergency Shell.
[  OK  ] Reached target Emergency Mode.
[  OK  ] Stopped dracut initqueue hook.
[  OK  ] Reached target Remote File Systems (Pre).
[  OK  ] Reached target Remote File Systems.
[  OK  ] Stopped dracut pre-trigger hook.
[  OK  ] Stopped dracut pre-udev hook.
[  OK  ] Stopped dracut cmdline hook.
Warning: /dev/disk/by-label/COS_LIVE does not exist
Warning: /dev/root does not exist

Generating "/run/initramfs/rdsosreport.txt"


Entering emergency moPress Enter for maintenance
(or press Control-D to continue):
```

**Comment by kkaempf** [comment] 2021-11-18 16:48
And `/run/initramfs/rdsosreport.txt` contains

```
+ cat /lib/dracut/dracut-049.1+suse.209.gebcf4f33-3.40.1
dracut-049.1+suse.209.gebcf4f33-3.40.1
+ cat /proc/cmdline
+ sed -e 's/\(ftp:\/\/.*\):.*@/\1:*******@/g;s/\(cifs:\/\/.*\):.*@/\1:*******@/g;s/cifspass=[^ ]*/cifspass=*******/g;s/iscsi:.*@/iscsi:******@/g;s/rd.iscsi.password=[^ ]*/rd.iscsi.passworda'
BOOT_IMAGE=(hd0,msdos1)/boot/kernel.xz cdroot root=live:CDLABEL=COS_LIVE rd.live.dir=/ rd.live.squashimg=rootfs.squashfs earlycon console=ttyS0,115200n8 rd.cos.disable
+ '[' -f /etc/cmdline ']'
+ for _i in /etc/cmdline.d/*.conf
+ '[' -f '/etc/cmdline.d/*.conf' ']'
+ break
+ cat /proc/self/mountinfo
1 1 0:2 / / rw shared:1 - rootfs rootfs rw
26 1 0:25 / /sys rw,nosuid,nodev,noexec,relatime shared:2 - sysfs sysfs rw
27 1 0:5 / /proc rw,nosuid,nodev,noexec,relatime shared:10 - proc proc rw
28 1 0:6 / /dev rw,nosuid,noexec shared:11 - devtmpfs devtmpfs rw,size=4096k,nr_inodes=65536,mode=755
29 26 0:7 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:3 - securityfs securityfs rw
30 28 0:26 / /dev/shm rw,nosuid,nodev shared:12 - tmpfs tmpfs rw

```

**Comment by mudler** [comment] 2021-11-19 14:42
Sadly I don't have a debug port available at the moment to collect logs. 

In my case the reboot is happening right after grub and supposedly initrd is being loaded. After grub I have blank screen and reboots follow in a matter of few seconds.

**Comment by mudler** [comment] 2021-11-24 13:02
update on my side: The issues I was having were cause by a bad PSU. Now it boots and loads initrd and tries to mount the partitions, and stops at COS_PERSISTENT as the image script doesn't create one automatically.. that's more left for documentation and I have couple of fixups which I'll open a PR for.

**Comment by mudler** [comment] 2021-11-24 16:01
For the odroid fixups, see https://github.com/rancher-sandbox/cOS-toolkit/pull/885 . I can successfully boot. I still have to test if all the functionalities are there ( upgrade, reset, etc. )

**Comment by mudler** [comment] 2021-11-25 15:53
Odroid update: there are some missing base packages, atm boot have no network and just few support available. I'm trying backing custom images with additional packages to find a good base set which is a base minimum that "works", similar work would be needed for the RPI, so this should be helpful when creating Docker images for those boards too.

**Closed** 2021-11-30 09:22 UTC
Labels: bug, blocked, ARM, rpi4
